require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AliasesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Alias. As you add validations to Alias, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AliasesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all aliases as @aliases" do
      alias = Alias.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:aliases)).to eq([alias])
    end
  end

  describe "GET show" do
    it "assigns the requested alias as @alias" do
      alias = Alias.create! valid_attributes
      get :show, {:id => alias.to_param}, valid_session
      expect(assigns(:alias)).to eq(alias)
    end
  end

  describe "GET new" do
    it "assigns a new alias as @alias" do
      get :new, {}, valid_session
      expect(assigns(:alias)).to be_a_new(Alias)
    end
  end

  describe "GET edit" do
    it "assigns the requested alias as @alias" do
      alias = Alias.create! valid_attributes
      get :edit, {:id => alias.to_param}, valid_session
      expect(assigns(:alias)).to eq(alias)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Alias" do
        expect {
          post :create, {:alias => valid_attributes}, valid_session
        }.to change(Alias, :count).by(1)
      end

      it "assigns a newly created alias as @alias" do
        post :create, {:alias => valid_attributes}, valid_session
        expect(assigns(:alias)).to be_a(Alias)
        expect(assigns(:alias)).to be_persisted
      end

      it "redirects to the created alias" do
        post :create, {:alias => valid_attributes}, valid_session
        expect(response).to redirect_to(Alias.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved alias as @alias" do
        post :create, {:alias => invalid_attributes}, valid_session
        expect(assigns(:alias)).to be_a_new(Alias)
      end

      it "re-renders the 'new' template" do
        post :create, {:alias => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested alias" do
        alias = Alias.create! valid_attributes
        put :update, {:id => alias.to_param, :alias => new_attributes}, valid_session
        alias.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested alias as @alias" do
        alias = Alias.create! valid_attributes
        put :update, {:id => alias.to_param, :alias => valid_attributes}, valid_session
        expect(assigns(:alias)).to eq(alias)
      end

      it "redirects to the alias" do
        alias = Alias.create! valid_attributes
        put :update, {:id => alias.to_param, :alias => valid_attributes}, valid_session
        expect(response).to redirect_to(alias)
      end
    end

    describe "with invalid params" do
      it "assigns the alias as @alias" do
        alias = Alias.create! valid_attributes
        put :update, {:id => alias.to_param, :alias => invalid_attributes}, valid_session
        expect(assigns(:alias)).to eq(alias)
      end

      it "re-renders the 'edit' template" do
        alias = Alias.create! valid_attributes
        put :update, {:id => alias.to_param, :alias => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested alias" do
      alias = Alias.create! valid_attributes
      expect {
        delete :destroy, {:id => alias.to_param}, valid_session
      }.to change(Alias, :count).by(-1)
    end

    it "redirects to the aliases list" do
      alias = Alias.create! valid_attributes
      delete :destroy, {:id => alias.to_param}, valid_session
      expect(response).to redirect_to(aliases_url)
    end
  end

end
